export const UPS_EFFICIENCY = 0.94;
export const KILO = 1000;
export const INDEX_E3M_START = 1;
export const INDEX_E3M_MOD_START = 6;
export const INDEX_E3L_START = 9;
export const BATTERY_INFO_START_INDEX = 41;
export const BATTERY_TYPES_QANTITY = 21;
export const BATTERY_INFO_END_INDEX =
  BATTERY_INFO_START_INDEX + BATTERY_TYPES_QANTITY;
export const BATTERY_POWER_START_INDEX = 8;
export const BATTERY_POWER_END_INDEX = BATTERY_POWER_START_INDEX + 6;
